services:
  db:
    image: postgres:18
    container_name: sports-league-db
    restart: unless-stopped
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql

  flyway:
    image: flyway/flyway:11
    container_name: sports-league-flyway
    depends_on:
      - db
    env_file:
      - .env
    environment:
      FLYWAY_URL: "jdbc:postgresql://db:5432/${POSTGRES_DB}"
      FLYWAY_USER: "${POSTGRES_USER}"
      FLYWAY_PASSWORD: "${POSTGRES_PASSWORD}"
      FLYWAY_CONNECT_RETRIES: "60"
      FLYWAY_BASELINE_ON_MIGRATE: "true"
    volumes:
      - ./db/migrations:/flyway/sql
    command: -locations=filesystem:/flyway/sql migrate

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: sports-league-backend
    restart: unless-stopped
    depends_on:
      - db
    env_file:
      - .env
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}"
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    command: uvicorn api.app.main:app --host 0.0.0.0 --port 8000 --reload


volumes:
  db_data:
